const mongoose = require('mongoose');
const Dish = require('./models/Dish');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/fittracker';

const dishes = [
    // BREAKFAST DISHES
    {
        name: 'Oatmeal with Berries',
        description: 'Creamy oatmeal topped with fresh berries and a drizzle of honey.',
        category: 'breakfast',
        calories: 280,
        protein: 8,
        carbs: 52,
        fats: 5,
        fiber: 6,
        ingredients: ['rolled oats', 'mixed berries', 'honey', 'almond milk'],
        instructions: 'Cook oats with almond milk, top with berries and honey.',
        prepTime: 5,
        cookTime: 5,
        servings: 1,
        tags: ['high-fiber', 'quick', 'healthy'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Scrambled Eggs with Toast',
        description: 'Fluffy scrambled eggs served with whole grain toast.',
        category: 'breakfast',
        calories: 320,
        protein: 18,
        carbs: 28,
        fats: 14,
        fiber: 4,
        ingredients: ['eggs', 'whole grain bread', 'butter', 'salt', 'pepper'],
        instructions: 'Scramble eggs, toast bread, serve together.',
        prepTime: 3,
        cookTime: 5,
        servings: 1,
        tags: ['high-protein', 'quick'],
        dishType: 'high-protein',
        dietaryType: 'eggetarian',
        contains: ['eggs', 'dairy'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Greek Yogurt Parfait',
        description: 'Layered Greek yogurt with granola and fresh fruits.',
        category: 'breakfast',
        calories: 250,
        protein: 15,
        carbs: 35,
        fats: 6,
        fiber: 4,
        ingredients: ['Greek yogurt', 'granola', 'strawberries', 'blueberries', 'honey'],
        instructions: 'Layer yogurt, fruits, and granola in a glass.',
        prepTime: 5,
        cookTime: 0,
        servings: 1,
        tags: ['high-protein', 'quick', 'no-cook'],
        dishType: 'high-protein',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Avocado Toast',
        description: 'Whole grain toast topped with mashed avocado, cherry tomatoes, and feta cheese.',
        category: 'breakfast',
        calories: 290,
        protein: 10,
        carbs: 32,
        fats: 15,
        fiber: 8,
        ingredients: ['whole grain bread', 'avocado', 'cherry tomatoes', 'feta cheese', 'lemon', 'salt'],
        instructions: 'Toast bread, mash avocado, top with tomatoes and feta.',
        prepTime: 5,
        cookTime: 2,
        servings: 1,
        tags: ['healthy', 'vegetarian'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Protein Pancakes',
        description: 'Fluffy pancakes made with protein powder and topped with fresh fruits.',
        category: 'breakfast',
        calories: 350,
        protein: 25,
        carbs: 40,
        fats: 8,
        fiber: 5,
        ingredients: ['protein powder', 'eggs', 'banana', 'oats', 'berries', 'maple syrup'],
        instructions: 'Blend ingredients, cook pancakes, top with fruits and syrup.',
        prepTime: 10,
        cookTime: 10,
        servings: 2,
        tags: ['high-protein', 'sweet'],
        dishType: 'high-protein',
        dietaryType: 'eggetarian',
        contains: ['eggs'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Chicken Sausage and Eggs',
        description: 'Grilled chicken sausage with scrambled eggs and vegetables.',
        category: 'breakfast',
        calories: 380,
        protein: 28,
        carbs: 8,
        fats: 24,
        fiber: 2,
        ingredients: ['chicken sausage', 'eggs', 'bell peppers', 'onions', 'olive oil'],
        instructions: 'Grill sausage, scramble eggs with vegetables, serve together.',
        prepTime: 5,
        cookTime: 12,
        servings: 1,
        tags: ['high-protein', 'keto-friendly'],
        dishType: 'high-protein',
        dietaryType: 'non-vegetarian',
        contains: ['chicken', 'eggs'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Smoothie Bowl',
        description: 'Thick smoothie bowl topped with granola, fruits, and nuts.',
        category: 'breakfast',
        calories: 320,
        protein: 12,
        carbs: 48,
        fats: 10,
        fiber: 7,
        ingredients: ['banana', 'berries', 'Greek yogurt', 'granola', 'almonds', 'chia seeds'],
        instructions: 'Blend fruits and yogurt, pour in bowl, top with granola and nuts.',
        prepTime: 10,
        cookTime: 0,
        servings: 1,
        tags: ['healthy', 'no-cook', 'high-fiber'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Vegetable Upma',
        description: 'Traditional Indian breakfast made with semolina and vegetables.',
        category: 'breakfast',
        calories: 280,
        protein: 8,
        carbs: 45,
        fats: 8,
        fiber: 4,
        ingredients: ['semolina', 'onions', 'carrots', 'peas', 'green chilies', 'mustard seeds', 'curry leaves'],
        instructions: 'Roast semolina, sauté vegetables, add semolina and water, cook until done.',
        prepTime: 10,
        cookTime: 15,
        servings: 2,
        tags: ['indian', 'vegetarian'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Poha',
        description: 'Flattened rice cooked with onions, peanuts, and spices.',
        category: 'breakfast',
        calories: 260,
        protein: 6,
        carbs: 42,
        fats: 7,
        fiber: 3,
        ingredients: ['poha', 'onions', 'peanuts', 'mustard seeds', 'turmeric', 'green chilies', 'lemon'],
        instructions: 'Soak poha, sauté with spices and vegetables, garnish with lemon.',
        prepTime: 5,
        cookTime: 10,
        servings: 2,
        tags: ['indian', 'vegetarian', 'quick'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Idli with Sambar',
        description: 'Steamed rice cakes served with lentil curry.',
        category: 'breakfast',
        calories: 220,
        protein: 8,
        carbs: 38,
        fats: 4,
        fiber: 5,
        ingredients: ['idli', 'toor dal', 'vegetables', 'tamarind', 'spices'],
        instructions: 'Steam idlis, prepare sambar with dal and vegetables.',
        prepTime: 30,
        cookTime: 20,
        servings: 2,
        tags: ['indian', 'vegetarian', 'healthy'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'indian'
    },

    // LUNCH DISHES
    {
        name: 'Grilled Chicken Breast with Quinoa',
        description: 'Lean grilled chicken served with quinoa and steamed vegetables.',
        category: 'lunch',
        calories: 420,
        protein: 38,
        carbs: 35,
        fats: 12,
        fiber: 5,
        ingredients: ['chicken breast', 'quinoa', 'broccoli', 'carrots', 'olive oil', 'lemon'],
        instructions: 'Grill chicken, cook quinoa, steam vegetables, serve together.',
        prepTime: 10,
        cookTime: 25,
        servings: 1,
        tags: ['high-protein', 'healthy'],
        dishType: 'high-protein',
        dietaryType: 'non-vegetarian',
        contains: ['chicken'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Vegetable Stir Fry with Brown Rice',
        description: 'Colorful vegetables stir-fried with tofu and served over brown rice.',
        category: 'lunch',
        calories: 380,
        protein: 15,
        carbs: 52,
        fats: 12,
        fiber: 8,
        ingredients: ['tofu', 'broccoli', 'bell peppers', 'carrots', 'brown rice', 'soy sauce', 'ginger', 'garlic'],
        instructions: 'Cook rice, stir-fry vegetables and tofu with sauce, serve over rice.',
        prepTime: 15,
        cookTime: 20,
        servings: 1,
        tags: ['vegetarian', 'high-fiber'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Salmon with Sweet Potato',
        description: 'Baked salmon fillet with roasted sweet potato and asparagus.',
        category: 'lunch',
        calories: 450,
        protein: 32,
        carbs: 38,
        fats: 18,
        fiber: 6,
        ingredients: ['salmon fillet', 'sweet potato', 'asparagus', 'olive oil', 'lemon', 'herbs'],
        instructions: 'Bake salmon, roast sweet potato and asparagus, serve together.',
        prepTime: 10,
        cookTime: 25,
        servings: 1,
        tags: ['high-protein', 'omega-3', 'healthy'],
        dishType: 'balanced',
        dietaryType: 'non-vegetarian',
        contains: ['fish'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Dal Rice',
        description: 'Lentil curry served with steamed basmati rice.',
        category: 'lunch',
        calories: 350,
        protein: 14,
        carbs: 58,
        fats: 8,
        fiber: 8,
        ingredients: ['toor dal', 'rice', 'onions', 'tomatoes', 'spices', 'ghee'],
        instructions: 'Cook dal with spices, prepare rice, serve together.',
        prepTime: 10,
        cookTime: 30,
        servings: 2,
        tags: ['indian', 'vegetarian', 'comfort-food'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Chicken Curry with Roti',
        description: 'Spicy chicken curry served with whole wheat roti.',
        category: 'lunch',
        calories: 480,
        protein: 32,
        carbs: 42,
        fats: 18,
        fiber: 5,
        ingredients: ['chicken', 'onions', 'tomatoes', 'yogurt', 'spices', 'whole wheat flour'],
        instructions: 'Cook chicken curry, prepare roti, serve together.',
        prepTime: 15,
        cookTime: 35,
        servings: 2,
        tags: ['indian', 'high-protein'],
        dishType: 'high-protein',
        dietaryType: 'non-vegetarian',
        contains: ['chicken', 'dairy'],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Vegetable Biryani',
        description: 'Fragrant basmati rice cooked with vegetables and aromatic spices.',
        category: 'lunch',
        calories: 420,
        protein: 10,
        carbs: 68,
        fats: 12,
        fiber: 6,
        ingredients: ['basmati rice', 'mixed vegetables', 'onions', 'yogurt', 'spices', 'ghee'],
        instructions: 'Parboil rice, layer with spiced vegetables, cook on dum.',
        prepTime: 20,
        cookTime: 40,
        servings: 3,
        tags: ['indian', 'vegetarian', 'flavorful'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Rajma Rice',
        description: 'Kidney bean curry served with steamed rice.',
        category: 'lunch',
        calories: 380,
        protein: 16,
        carbs: 62,
        fats: 8,
        fiber: 12,
        ingredients: ['kidney beans', 'rice', 'onions', 'tomatoes', 'spices'],
        instructions: 'Soak and cook beans, prepare curry, serve with rice.',
        prepTime: 30,
        cookTime: 45,
        servings: 3,
        tags: ['indian', 'vegetarian', 'high-fiber'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Chole Bhature',
        description: 'Spiced chickpea curry served with fluffy fried bread.',
        category: 'lunch',
        calories: 520,
        protein: 14,
        carbs: 72,
        fats: 18,
        fiber: 10,
        ingredients: ['chickpeas', 'all-purpose flour', 'yogurt', 'onions', 'spices', 'oil'],
        instructions: 'Cook chole, prepare bhature dough, fry bhature, serve together.',
        prepTime: 20,
        cookTime: 30,
        servings: 2,
        tags: ['indian', 'vegetarian', 'indulgent'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Mediterranean Bowl',
        description: 'Quinoa bowl with chickpeas, feta, olives, and vegetables.',
        category: 'lunch',
        calories: 400,
        protein: 16,
        carbs: 48,
        fats: 14,
        fiber: 10,
        ingredients: ['quinoa', 'chickpeas', 'feta cheese', 'olives', 'cucumber', 'tomatoes', 'olive oil'],
        instructions: 'Cook quinoa, assemble bowl with all ingredients, drizzle with olive oil.',
        prepTime: 15,
        cookTime: 15,
        servings: 1,
        tags: ['mediterranean', 'vegetarian', 'healthy'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'mediterranean'
    },
    {
        name: 'Turkey Wrap',
        description: 'Whole wheat wrap filled with turkey, vegetables, and hummus.',
        category: 'lunch',
        calories: 360,
        protein: 28,
        carbs: 38,
        fats: 10,
        fiber: 6,
        ingredients: ['whole wheat tortilla', 'turkey slices', 'lettuce', 'tomatoes', 'hummus', 'cucumber'],
        instructions: 'Spread hummus on tortilla, add turkey and vegetables, roll tightly.',
        prepTime: 5,
        cookTime: 0,
        servings: 1,
        tags: ['high-protein', 'quick', 'portable'],
        dishType: 'high-protein',
        dietaryType: 'non-vegetarian',
        contains: ['turkey'],
        restrictions: [],
        cuisineType: 'international'
    },

    // DINNER DISHES
    {
        name: 'Grilled Fish with Vegetables',
        description: 'Grilled fish fillet with roasted seasonal vegetables.',
        category: 'dinner',
        calories: 380,
        protein: 30,
        carbs: 25,
        fats: 16,
        fiber: 5,
        ingredients: ['fish fillet', 'zucchini', 'bell peppers', 'broccoli', 'olive oil', 'lemon', 'herbs'],
        instructions: 'Marinate fish, grill fish and vegetables, serve together.',
        prepTime: 15,
        cookTime: 20,
        servings: 1,
        tags: ['high-protein', 'light', 'healthy'],
        dishType: 'balanced',
        dietaryType: 'non-vegetarian',
        contains: ['fish'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Vegetable Pulao',
        description: 'Fragrant rice cooked with mixed vegetables and whole spices.',
        category: 'dinner',
        calories: 320,
        protein: 8,
        carbs: 58,
        fats: 8,
        fiber: 4,
        ingredients: ['basmati rice', 'mixed vegetables', 'onions', 'whole spices', 'ghee'],
        instructions: 'Sauté vegetables, add rice and water, cook until done.',
        prepTime: 15,
        cookTime: 25,
        servings: 3,
        tags: ['indian', 'vegetarian', 'comfort-food'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Chicken Tikka Masala',
        description: 'Creamy tomato-based curry with grilled chicken pieces.',
        category: 'dinner',
        calories: 450,
        protein: 35,
        carbs: 28,
        fats: 22,
        fiber: 3,
        ingredients: ['chicken', 'tomatoes', 'cream', 'onions', 'spices', 'butter'],
        instructions: 'Marinate and grill chicken, prepare masala, combine and simmer.',
        prepTime: 30,
        cookTime: 30,
        servings: 2,
        tags: ['indian', 'high-protein', 'creamy'],
        dishType: 'high-protein',
        dietaryType: 'non-vegetarian',
        contains: ['chicken', 'dairy'],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Palak Paneer',
        description: 'Spinach curry with Indian cottage cheese cubes.',
        category: 'dinner',
        calories: 320,
        protein: 18,
        carbs: 15,
        fats: 20,
        fiber: 5,
        ingredients: ['spinach', 'paneer', 'onions', 'tomatoes', 'spices', 'cream'],
        instructions: 'Blanch spinach, prepare curry, add fried paneer cubes.',
        prepTime: 15,
        cookTime: 25,
        servings: 2,
        tags: ['indian', 'vegetarian', 'high-protein'],
        dishType: 'high-protein',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Vegetable Curry with Roti',
        description: 'Mixed vegetable curry served with whole wheat roti.',
        category: 'dinner',
        calories: 340,
        protein: 10,
        carbs: 52,
        fats: 10,
        fiber: 8,
        ingredients: ['mixed vegetables', 'onions', 'tomatoes', 'spices', 'whole wheat flour'],
        instructions: 'Cook vegetable curry, prepare roti, serve together.',
        prepTime: 15,
        cookTime: 30,
        servings: 2,
        tags: ['indian', 'vegetarian', 'healthy'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Baked Chicken Thighs',
        description: 'Herb-marinated chicken thighs baked with root vegetables.',
        category: 'dinner',
        calories: 420,
        protein: 32,
        carbs: 22,
        fats: 20,
        fiber: 4,
        ingredients: ['chicken thighs', 'potatoes', 'carrots', 'herbs', 'olive oil', 'lemon'],
        instructions: 'Marinate chicken, arrange with vegetables, bake until golden.',
        prepTime: 20,
        cookTime: 40,
        servings: 2,
        tags: ['high-protein', 'comfort-food'],
        dishType: 'high-protein',
        dietaryType: 'non-vegetarian',
        contains: ['chicken'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Mushroom Risotto',
        description: 'Creamy Italian rice dish with sautéed mushrooms.',
        category: 'dinner',
        calories: 380,
        protein: 12,
        carbs: 52,
        fats: 14,
        fiber: 3,
        ingredients: ['arborio rice', 'mushrooms', 'onions', 'white wine', 'parmesan', 'butter'],
        instructions: 'Sauté mushrooms, cook rice gradually adding stock, finish with cheese.',
        prepTime: 10,
        cookTime: 30,
        servings: 2,
        tags: ['italian', 'vegetarian', 'creamy'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Dal Tadka',
        description: 'Tempered lentil curry served with rice or roti.',
        category: 'dinner',
        calories: 280,
        protein: 12,
        carbs: 42,
        fats: 8,
        fiber: 8,
        ingredients: ['toor dal', 'onions', 'tomatoes', 'garlic', 'spices', 'ghee'],
        instructions: 'Cook dal, prepare tadka with spices, combine and serve.',
        prepTime: 10,
        cookTime: 25,
        servings: 2,
        tags: ['indian', 'vegetarian', 'protein-rich'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Egg Curry',
        description: 'Hard-boiled eggs in spicy tomato-based curry.',
        category: 'dinner',
        calories: 320,
        protein: 18,
        carbs: 15,
        fats: 18,
        fiber: 3,
        ingredients: ['eggs', 'onions', 'tomatoes', 'spices', 'oil'],
        instructions: 'Boil eggs, prepare curry, add eggs and simmer.',
        prepTime: 10,
        cookTime: 20,
        servings: 2,
        tags: ['indian', 'high-protein', 'quick'],
        dishType: 'high-protein',
        dietaryType: 'eggetarian',
        contains: ['eggs'],
        restrictions: [],
        cuisineType: 'indian'
    },
    {
        name: 'Paneer Butter Masala',
        description: 'Rich and creamy curry with paneer cubes.',
        category: 'dinner',
        calories: 380,
        protein: 20,
        carbs: 18,
        fats: 24,
        fiber: 3,
        ingredients: ['paneer', 'tomatoes', 'cream', 'butter', 'spices', 'cashews'],
        instructions: 'Fry paneer, prepare masala, add paneer and cream.',
        prepTime: 15,
        cookTime: 25,
        servings: 2,
        tags: ['indian', 'vegetarian', 'indulgent'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'indian'
    },

    // SNACKS
    {
        name: 'Apple with Almond Butter',
        description: 'Fresh apple slices served with almond butter.',
        category: 'snack',
        calories: 200,
        protein: 6,
        carbs: 28,
        fats: 10,
        fiber: 6,
        ingredients: ['apple', 'almond butter'],
        instructions: 'Slice apple, serve with almond butter.',
        prepTime: 2,
        cookTime: 0,
        servings: 1,
        tags: ['healthy', 'quick', 'no-cook'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Greek Yogurt with Nuts',
        description: 'Greek yogurt topped with mixed nuts and honey.',
        category: 'snack',
        calories: 220,
        protein: 15,
        carbs: 18,
        fats: 10,
        fiber: 3,
        ingredients: ['Greek yogurt', 'almonds', 'walnuts', 'honey'],
        instructions: 'Top yogurt with nuts and drizzle honey.',
        prepTime: 2,
        cookTime: 0,
        servings: 1,
        tags: ['high-protein', 'quick', 'no-cook'],
        dishType: 'high-protein',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Hummus with Veggies',
        description: 'Creamy hummus served with fresh vegetable sticks.',
        category: 'snack',
        calories: 180,
        protein: 8,
        carbs: 22,
        fats: 8,
        fiber: 8,
        ingredients: ['chickpeas', 'tahini', 'lemon', 'carrots', 'cucumber', 'bell peppers'],
        instructions: 'Blend chickpeas with tahini and lemon, serve with vegetables.',
        prepTime: 10,
        cookTime: 0,
        servings: 1,
        tags: ['vegetarian', 'high-fiber', 'healthy'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Protein Smoothie',
        description: 'Blended smoothie with protein powder, banana, and berries.',
        category: 'snack',
        calories: 250,
        protein: 20,
        carbs: 32,
        fats: 4,
        fiber: 5,
        ingredients: ['protein powder', 'banana', 'berries', 'almond milk', 'spinach'],
        instructions: 'Blend all ingredients until smooth.',
        prepTime: 5,
        cookTime: 0,
        servings: 1,
        tags: ['high-protein', 'quick', 'portable'],
        dishType: 'high-protein',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Roasted Chickpeas',
        description: 'Crispy roasted chickpeas seasoned with spices.',
        category: 'snack',
        calories: 150,
        protein: 8,
        carbs: 22,
        fats: 4,
        fiber: 6,
        ingredients: ['chickpeas', 'olive oil', 'salt', 'paprika', 'cumin'],
        instructions: 'Toss chickpeas with oil and spices, roast until crispy.',
        prepTime: 5,
        cookTime: 25,
        servings: 1,
        tags: ['vegetarian', 'high-fiber', 'crunchy'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Trail Mix',
        description: 'Mixed nuts, dried fruits, and dark chocolate chips.',
        category: 'snack',
        calories: 200,
        protein: 6,
        carbs: 20,
        fats: 12,
        fiber: 4,
        ingredients: ['almonds', 'walnuts', 'raisins', 'dark chocolate chips'],
        instructions: 'Mix all ingredients together.',
        prepTime: 2,
        cookTime: 0,
        servings: 1,
        tags: ['portable', 'energy-boost'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Boiled Eggs',
        description: 'Hard-boiled eggs seasoned with salt and pepper.',
        category: 'snack',
        calories: 140,
        protein: 12,
        carbs: 1,
        fats: 10,
        fiber: 0,
        ingredients: ['eggs', 'salt', 'pepper'],
        instructions: 'Boil eggs for 8-10 minutes, peel and season.',
        prepTime: 2,
        cookTime: 10,
        servings: 2,
        tags: ['high-protein', 'quick', 'portable'],
        dishType: 'high-protein',
        dietaryType: 'eggetarian',
        contains: ['eggs'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Cottage Cheese with Fruits',
        description: 'Cottage cheese topped with fresh fruits and honey.',
        category: 'snack',
        calories: 180,
        protein: 14,
        carbs: 22,
        fats: 4,
        fiber: 2,
        ingredients: ['cottage cheese', 'berries', 'honey'],
        instructions: 'Top cottage cheese with fruits and drizzle honey.',
        prepTime: 3,
        cookTime: 0,
        servings: 1,
        tags: ['high-protein', 'quick', 'no-cook'],
        dishType: 'high-protein',
        dietaryType: 'vegetarian',
        contains: ['dairy'],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Banana with Peanut Butter',
        description: 'Banana slices topped with natural peanut butter.',
        category: 'snack',
        calories: 240,
        protein: 8,
        carbs: 32,
        fats: 12,
        fiber: 6,
        ingredients: ['banana', 'peanut butter'],
        instructions: 'Slice banana, top with peanut butter.',
        prepTime: 2,
        cookTime: 0,
        servings: 1,
        tags: ['quick', 'energy-boost', 'no-cook'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'international'
    },
    {
        name: 'Vegetable Soup',
        description: 'Warm vegetable soup with herbs and spices.',
        category: 'snack',
        calories: 120,
        protein: 4,
        carbs: 18,
        fats: 4,
        fiber: 4,
        ingredients: ['mixed vegetables', 'vegetable broth', 'herbs', 'spices'],
        instructions: 'Sauté vegetables, add broth, simmer until tender.',
        prepTime: 10,
        cookTime: 20,
        servings: 1,
        tags: ['low-calorie', 'warming', 'healthy'],
        dishType: 'balanced',
        dietaryType: 'vegetarian',
        contains: [],
        restrictions: [],
        cuisineType: 'international'
    }
];

async function seedDishes() {
    try {
        await mongoose.connect(MONGO_URI);
        console.log('Connected to MongoDB');

        // Clear existing dishes
        await Dish.deleteMany({});
        console.log('Cleared existing dishes');

        // Insert new dishes
        await Dish.insertMany(dishes);
        console.log(`Successfully seeded ${dishes.length} dishes`);

        await mongoose.connection.close();
        console.log('Database connection closed');
        process.exit(0);
    } catch (error) {
        console.error('Error seeding dishes:', error);
        process.exit(1);
    }
}

seedDishes();

